# This file is a template, and might need editing before it works on your project.
variables:
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_DRIVER: overlay2
  MOUNT_POINT: /builds/$CI_PROJECT_PATH/mnt

docker-build-master:
  # Official docker image.
  image: docker:19.03.0
  stage: build
  services:
    - docker:19.03.0-dind
  script:
    - mkdir -p "$MOUNT_POINT"
    - docker build -f "apps/classifieds-lambda/Dockerfile" -e AWS_ACCESS_KEY="$AWS_ACCESS_KEY" -e AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY" . 
  only:
    - master
  tags:
    - docker
    - azure
    - classifieds
    - smeskey
