# This file is a template, and might need editing before it works on your project.
variables:
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_DRIVER: overlay2

stages:
  - install-node
  - install-app-packages
  - build-app

.base:
  image: docker:19.03.0
  services:
    - docker:19.03.0-dind
  only:
    - master
  tags:
    - docker
    - azure
    - classifieds
    - smeskey

install-node:
  extends: .base
  stage: install-node
  script:
    - apt-get update
    - apt-get -y upgrade
    - apt-get update
    - apt-get -y install curl dirmngr apt-transport-https lsb-release ca-certificates
    - curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
    - apt-get -y install nodejs

install-app-packages:
  extends: .base
  stage: install-app-packages
  script:
    - npm install -g serverless
    - npm install

build-app:
  extends: .base
  stage: build-app
  script:
    - ng run classifieds:build --configuration="dev" --baseHref="/dev/" --deployUrl="/dev/"
    - ng run classifieds:server --configuration="dev" --deployUrl="/dev/"
    - ng run classifieds-lambda:build
