image: node:10.16.3

pages:
  cache:
    paths:
    - node_modules/

  stage: deploy
  script:
  - npm install -g @angular/cli@8.3.6
  - npm install
  - ng build classifieds --configuration="dev" --baseHref="/classifieds-ui" --deployUrl="/classifieds-ui/"
  - mkdir public
  - mv dist/apps/classifieds/* public/
  artifacts:
    paths:
    - public
  only:
  - master
  - pages